// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package handler

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HandlerClient is the client API for Handler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HandlerClient interface {
	HandleTask(ctx context.Context, in *HandleTaskRequest, opts ...grpc.CallOption) (*HandleTaskResponse, error)
	HandleJob(ctx context.Context, in *HandleJobRequest, opts ...grpc.CallOption) (*HandleJobResponse, error)
}

type handlerClient struct {
	cc grpc.ClientConnInterface
}

func NewHandlerClient(cc grpc.ClientConnInterface) HandlerClient {
	return &handlerClient{cc}
}

func (c *handlerClient) HandleTask(ctx context.Context, in *HandleTaskRequest, opts ...grpc.CallOption) (*HandleTaskResponse, error) {
	out := new(HandleTaskResponse)
	err := c.cc.Invoke(ctx, "/aserto.task.handler.Handler/HandleTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handlerClient) HandleJob(ctx context.Context, in *HandleJobRequest, opts ...grpc.CallOption) (*HandleJobResponse, error) {
	out := new(HandleJobResponse)
	err := c.cc.Invoke(ctx, "/aserto.task.handler.Handler/HandleJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HandlerServer is the server API for Handler service.
// All implementations should embed UnimplementedHandlerServer
// for forward compatibility
type HandlerServer interface {
	HandleTask(context.Context, *HandleTaskRequest) (*HandleTaskResponse, error)
	HandleJob(context.Context, *HandleJobRequest) (*HandleJobResponse, error)
}

// UnimplementedHandlerServer should be embedded to have forward compatible implementations.
type UnimplementedHandlerServer struct {
}

func (UnimplementedHandlerServer) HandleTask(context.Context, *HandleTaskRequest) (*HandleTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleTask not implemented")
}
func (UnimplementedHandlerServer) HandleJob(context.Context, *HandleJobRequest) (*HandleJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleJob not implemented")
}

// UnsafeHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HandlerServer will
// result in compilation errors.
type UnsafeHandlerServer interface {
	mustEmbedUnimplementedHandlerServer()
}

func RegisterHandlerServer(s grpc.ServiceRegistrar, srv HandlerServer) {
	s.RegisterService(&Handler_ServiceDesc, srv)
}

func _Handler_HandleTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandlerServer).HandleTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aserto.task.handler.Handler/HandleTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandlerServer).HandleTask(ctx, req.(*HandleTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Handler_HandleJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandlerServer).HandleJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aserto.task.handler.Handler/HandleJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandlerServer).HandleJob(ctx, req.(*HandleJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Handler_ServiceDesc is the grpc.ServiceDesc for Handler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Handler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aserto.task.handler.Handler",
	HandlerType: (*HandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleTask",
			Handler:    _Handler_HandleTask_Handler,
		},
		{
			MethodName: "HandleJob",
			Handler:    _Handler_HandleJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aserto/task/handler/handler.proto",
}
