// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package system

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SystemClient is the client API for System service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SystemClient interface {
	TenantConfig(ctx context.Context, in *TenantConfigRequest, opts ...grpc.CallOption) (*TenantConfigResponse, error)
	GetRuntime(ctx context.Context, in *GetRuntimeRequest, opts ...grpc.CallOption) (*GetRuntimeResponse, error)
	SetupRuntime(ctx context.Context, in *SetupRuntimeRequest, opts ...grpc.CallOption) (*SetupRuntimeResponse, error)
}

type systemClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemClient(cc grpc.ClientConnInterface) SystemClient {
	return &systemClient{cc}
}

func (c *systemClient) TenantConfig(ctx context.Context, in *TenantConfigRequest, opts ...grpc.CallOption) (*TenantConfigResponse, error) {
	out := new(TenantConfigResponse)
	err := c.cc.Invoke(ctx, "/aserto.authorizer.system.System/TenantConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemClient) GetRuntime(ctx context.Context, in *GetRuntimeRequest, opts ...grpc.CallOption) (*GetRuntimeResponse, error) {
	out := new(GetRuntimeResponse)
	err := c.cc.Invoke(ctx, "/aserto.authorizer.system.System/GetRuntime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemClient) SetupRuntime(ctx context.Context, in *SetupRuntimeRequest, opts ...grpc.CallOption) (*SetupRuntimeResponse, error) {
	out := new(SetupRuntimeResponse)
	err := c.cc.Invoke(ctx, "/aserto.authorizer.system.System/SetupRuntime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemServer is the server API for System service.
// All implementations should embed UnimplementedSystemServer
// for forward compatibility
type SystemServer interface {
	TenantConfig(context.Context, *TenantConfigRequest) (*TenantConfigResponse, error)
	GetRuntime(context.Context, *GetRuntimeRequest) (*GetRuntimeResponse, error)
	SetupRuntime(context.Context, *SetupRuntimeRequest) (*SetupRuntimeResponse, error)
}

// UnimplementedSystemServer should be embedded to have forward compatible implementations.
type UnimplementedSystemServer struct {
}

func (UnimplementedSystemServer) TenantConfig(context.Context, *TenantConfigRequest) (*TenantConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TenantConfig not implemented")
}
func (UnimplementedSystemServer) GetRuntime(context.Context, *GetRuntimeRequest) (*GetRuntimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRuntime not implemented")
}
func (UnimplementedSystemServer) SetupRuntime(context.Context, *SetupRuntimeRequest) (*SetupRuntimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetupRuntime not implemented")
}

// UnsafeSystemServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemServer will
// result in compilation errors.
type UnsafeSystemServer interface {
	mustEmbedUnimplementedSystemServer()
}

func RegisterSystemServer(s grpc.ServiceRegistrar, srv SystemServer) {
	s.RegisterService(&System_ServiceDesc, srv)
}

func _System_TenantConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServer).TenantConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aserto.authorizer.system.System/TenantConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServer).TenantConfig(ctx, req.(*TenantConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _System_GetRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServer).GetRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aserto.authorizer.system.System/GetRuntime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServer).GetRuntime(ctx, req.(*GetRuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _System_SetupRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupRuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServer).SetupRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aserto.authorizer.system.System/SetupRuntime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServer).SetupRuntime(ctx, req.(*SetupRuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// System_ServiceDesc is the grpc.ServiceDesc for System service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var System_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aserto.authorizer.system.System",
	HandlerType: (*SystemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TenantConfig",
			Handler:    _System_TenantConfig_Handler,
		},
		{
			MethodName: "GetRuntime",
			Handler:    _System_GetRuntime_Handler,
		},
		{
			MethodName: "SetupRuntime",
			Handler:    _System_SetupRuntime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aserto/authorizer/system/system.proto",
}
