// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package policy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PolicyClient is the client API for Policy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PolicyClient interface {
	ListPolicyRefs(ctx context.Context, in *ListPolicyRefsRequest, opts ...grpc.CallOption) (*ListPolicyRefsResponse, error)
	CreatePolicyRef(ctx context.Context, in *CreatePolicyRefRequest, opts ...grpc.CallOption) (*CreatePolicyRefResponse, error)
	DeletePolicyRef(ctx context.Context, in *DeletePolicyRefRequest, opts ...grpc.CallOption) (*DeletePolicyRefResponse, error)
}

type policyClient struct {
	cc grpc.ClientConnInterface
}

func NewPolicyClient(cc grpc.ClientConnInterface) PolicyClient {
	return &policyClient{cc}
}

func (c *policyClient) ListPolicyRefs(ctx context.Context, in *ListPolicyRefsRequest, opts ...grpc.CallOption) (*ListPolicyRefsResponse, error) {
	out := new(ListPolicyRefsResponse)
	err := c.cc.Invoke(ctx, "/aserto.tenant.policy.Policy/ListPolicyRefs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyClient) CreatePolicyRef(ctx context.Context, in *CreatePolicyRefRequest, opts ...grpc.CallOption) (*CreatePolicyRefResponse, error) {
	out := new(CreatePolicyRefResponse)
	err := c.cc.Invoke(ctx, "/aserto.tenant.policy.Policy/CreatePolicyRef", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyClient) DeletePolicyRef(ctx context.Context, in *DeletePolicyRefRequest, opts ...grpc.CallOption) (*DeletePolicyRefResponse, error) {
	out := new(DeletePolicyRefResponse)
	err := c.cc.Invoke(ctx, "/aserto.tenant.policy.Policy/DeletePolicyRef", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PolicyServer is the server API for Policy service.
// All implementations should embed UnimplementedPolicyServer
// for forward compatibility
type PolicyServer interface {
	ListPolicyRefs(context.Context, *ListPolicyRefsRequest) (*ListPolicyRefsResponse, error)
	CreatePolicyRef(context.Context, *CreatePolicyRefRequest) (*CreatePolicyRefResponse, error)
	DeletePolicyRef(context.Context, *DeletePolicyRefRequest) (*DeletePolicyRefResponse, error)
}

// UnimplementedPolicyServer should be embedded to have forward compatible implementations.
type UnimplementedPolicyServer struct {
}

func (UnimplementedPolicyServer) ListPolicyRefs(context.Context, *ListPolicyRefsRequest) (*ListPolicyRefsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPolicyRefs not implemented")
}
func (UnimplementedPolicyServer) CreatePolicyRef(context.Context, *CreatePolicyRefRequest) (*CreatePolicyRefResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePolicyRef not implemented")
}
func (UnimplementedPolicyServer) DeletePolicyRef(context.Context, *DeletePolicyRefRequest) (*DeletePolicyRefResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePolicyRef not implemented")
}

// UnsafePolicyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PolicyServer will
// result in compilation errors.
type UnsafePolicyServer interface {
	mustEmbedUnimplementedPolicyServer()
}

func RegisterPolicyServer(s grpc.ServiceRegistrar, srv PolicyServer) {
	s.RegisterService(&Policy_ServiceDesc, srv)
}

func _Policy_ListPolicyRefs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPolicyRefsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServer).ListPolicyRefs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aserto.tenant.policy.Policy/ListPolicyRefs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServer).ListPolicyRefs(ctx, req.(*ListPolicyRefsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Policy_CreatePolicyRef_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePolicyRefRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServer).CreatePolicyRef(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aserto.tenant.policy.Policy/CreatePolicyRef",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServer).CreatePolicyRef(ctx, req.(*CreatePolicyRefRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Policy_DeletePolicyRef_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePolicyRefRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServer).DeletePolicyRef(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aserto.tenant.policy.Policy/DeletePolicyRef",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServer).DeletePolicyRef(ctx, req.(*DeletePolicyRefRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Policy_ServiceDesc is the grpc.ServiceDesc for Policy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Policy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aserto.tenant.policy.Policy",
	HandlerType: (*PolicyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPolicyRefs",
			Handler:    _Policy_ListPolicyRefs_Handler,
		},
		{
			MethodName: "CreatePolicyRef",
			Handler:    _Policy_CreatePolicyRef_Handler,
		},
		{
			MethodName: "DeletePolicyRef",
			Handler:    _Policy_DeletePolicyRef_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aserto/tenant/policy/policy.proto",
}
